
services:
  main:
    container_name: main

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - ./.production.env

    volumes:
      - .:/WB
      - /WB/node_modules

    networks:
      - bridge

    ports:
      - 7000:7000

    depends_on:
      - postgres

    restart: always

  postgres:
    container_name: postgres

    image: postgres:16

    env_file:
      - .production.env

    environment:
      PG_DATA: C:\Program Files\PostgreSQL\16\data

    networks:
      - bridge

    ports:
      - 5432:1234

    volumes:
      - /var/lib/postgresql/data

    restart: always

volumes:
  pgdata:

networks:
  bridge:
    driver : "bridge"
    external: true
